### ISSUE TITLE
The resulting UI file can be invalid

### ISSUE THREAD

**Issue by wwmayer** [chennes/QtUIXmlCleaner#1]
When applying the cleaner on this file it creates an invalid file: https://raw.githubusercontent.com/FreeCAD/FreeCAD/f46154e17b40af0c2aa4c6f7c03b5ce0172922ba/src/Mod/PartDesign/Gui/TaskPocketParameters.ui

It produces this content in line 18 + 19
```
    <layout class="QGridLayout" name="gridLayout">
    </layout>
```
and afterwards (line 20ff) the item elements appear.

**Comment by chennes** [comment]
Thanks for the report. Are you running 1.0.2? And on Linux, I believe? Which options did you have enabled when it gave you that output?

**Comment by wwmayer** [comment]
I think it was version 1.0.1

Now when pulling the latest changes I can build a version 1.0.2 but not the latest commit in master c8ad4867e1d68. The last commit that I can still build is 1690b065181f and with the next commit I get a couple of Qt (I have 5.9.5) related errors because QByteArray doesn't provide a compare() function

> Which options did you have enabled when it gave you that output?

I have only set the Sort option and uinchecked the other two.

OK, let my try to build the latest version and then I can check again if the output is still invalid.

**Comment by chennes** [comment]
> Now when pulling the latest changes I can build a version 1.0.2 but not the latest commit in master [c8ad486](https://github.com/chennes/QtUIXmlCleaner/commit/c8ad4867e1d68a1e5b01862aa7a7c404c496153a). The last commit that I can still build is [1690b06](https://github.com/chennes/QtUIXmlCleaner/commit/1690b065181f5c957e4275fb6bd453b43b6cc102) and with the next commit I get a couple of Qt (I have 5.9.5) related errors because QByteArray doesn't provide a compare() function

OK, I can add a check for older versions of Qt and hand-code that comparison, I think that should be straightforward. Thanks again for testing.

**Comment by chennes** [comment]
Commit c0d618d adds in support for older versions of Qt by hand-coding the byte comparison in TestCleaner.cpp -- I am testing in 5.15, so please let me know if 5.9 works now, or if there are other changes I should make.

**Comment by wwmayer** [comment]
OK, so I quickly hacked in the changes to successfully build the version.
The changes I need to make:
* comment out the include of the filesystem header and `std::filesystem::copy(_infile, _infile + ".backup");`
* comment out all occurrences of QByteArray::compare in TestCleaner.cpp

According to https://en.cppreference.com/w/cpp/filesystem it requires C++17. So, I don't know how you want to proceed with this requirement:
* you can force a compiler that supports C++17
* you can use QFile instead
* for older compilers you can use boost and for newer compilers std

EDIT: On my Ubuntu Bionic system I also have clang 10 and 11 that support C++17. So, if you want to avoid all the extra work just change the CMake file to require a C++17 compiler

**Comment by wwmayer** [comment]
> Commit c0d618d adds in support for older versions of Qt by hand-coding the byte comparison in TestCleaner.cpp

Thanks, this fixes the Qt errors.

I have quickly tested with the new version and the corrupted ui file is fixed. So, sorry for the noise.

**Comment by chennes** [comment]
> EDIT: On my Ubuntu Bionic system I also have clang 10 and 11 that support C++17. So, if you want to avoid all the extra work just change the CMake file to require a C++17 compiler

OK, if that works for you that's what I'll go with.

**Comment by chennes** [comment]
Commit c0d4dc4 tweaks the CMake script to make C++17 a hard requirement, and to move the C++20 option to a new CMake flag.
